// wk-ant-admin/src/pages/platform/sys/log/index.tsx
import {
  DeleteOutlined,
  EyeOutlined,
} from '@ant-design/icons';
import type { ActionType, ProColumns } from '@ant-design/pro-components';
import { PageContainer } from '@ant-design/pro-components';
import { useAccess } from '@umijs/max';
import {
  App,
  Button,
  Descriptions,
  Drawer,
  Tag,
  Typography,
} from 'antd';
import dayjs from 'dayjs';
import * as React from 'react';
import PlatformProTable from '@/components/PlatformProTable';
import { clearLogs, deleteLog, getLogMeta, getLogPage } from '@/services/budiot/sys/log';
import type {
  BudiotAppOption,
  SysLogRecord,
  SysLogTypeOption,
} from '@/services/budiot/typing';

type LogTableParams = {
  current?: number;
  pageSize?: number;
  appId?: string;
  type?: string;
  status?: string;
  loginname?: string;
  username?: string;
  tag?: string;
  msg?: string;
  dateRange?: [dayjs.Dayjs, dayjs.Dayjs];
};

const getSortParams = (
  sort: Record<string, 'ascend' | 'descend' | null>,
  defaultField: string,
) => {
  const current = Object.entries(sort || {}).find(([, value]) => value);
  return {
    pageOrderName: current?.[0] || defaultField,
    pageOrderBy: current?.[1] === 'ascend' ? 'ascending' : 'descending',
  };
};

const LogPage = () => {
  const access = useAccess();
  const { modal } = App.useApp();
  const actionRef = React.useRef<ActionType>(null);
  const latestFiltersRef = React.useRef<Record<string, unknown>>({
    appId: '',
    type: '',
    status: '',
    loginname: '',
    username: '',
    tag: '',
    msg: '',
    beginTime: '',
    endTime: '',
  });
  const latestSortRef = React.useRef({
    pageOrderName: 'createdAt',
    pageOrderBy: 'descending',
  });
  const [metaLoading, setMetaLoading] = React.useState(false);
  const [apps, setApps] = React.useState<BudiotAppOption[]>([]);
  const [types, setTypes] = React.useState<SysLogTypeOption[]>([]);
  const [detailRecord, setDetailRecord] = React.useState<SysLogRecord>();

  React.useEffect(() => {
    const initialize = async () => {
      setMetaLoading(true);
      try {
        const response = await getLogMeta();
        setApps(response.data.apps || []);
        setTypes(response.data.types || []);
      } finally {
        setMetaLoading(false);
      }
    };

    initialize().catch(() => undefined);
  }, []);

  const columns = React.useMemo<ProColumns<SysLogRecord>[]>(
    () => [
      {
        title: '日志类型',
        dataIndex: 'type',
        valueType: 'select',
        initialValue: '',
        fieldProps: {
          loading: metaLoading,
          options: [
            { label: '全部日志', value: '' },
            ...types.map((item) => ({ label: item.text, value: item.value })),
          ],
          onChange: () => actionRef.current?.reload(),
        },
        width: 120,
        render: (_, record) => types.find((item) => item.value === record.type)?.text || record.type || '-',
      },
      {
        title: '应用',
        dataIndex: 'appId',
        hideInTable: true,
        valueType: 'select',
        fieldProps: {
          loading: metaLoading,
          allowClear: true,
          options: apps.map((item) => ({ label: item.name, value: item.id })),
          onChange: () => actionRef.current?.reload(),
        },
      },
      {
        title: '操作状态',
        dataIndex: 'status',
        hideInTable: true,
        valueType: 'select',
        initialValue: '',
        fieldProps: {
          options: [
            { label: '全部', value: '' },
            { label: '成功', value: 'success' },
            { label: '失败', value: 'exception' },
          ],
        },
      },
      {
        title: '用户姓名',
        dataIndex: 'username',
        hideInTable: true,
      },
      {
        title: '用户名',
        dataIndex: 'loginname',
        hideInTable: true,
      },
      {
        title: '功能模块',
        dataIndex: 'tag',
        width: 120,
        ellipsis: true,
      },
      {
        title: '日志内容',
        dataIndex: 'msg',
        ellipsis: true,
      },
      {
        title: '操作时间',
        dataIndex: 'dateRange',
        hideInTable: true,
        valueType: 'dateTimeRange',
        search: {
          transform: (value) => ({
            beginTime: value?.[0]?.valueOf?.() || '',
            endTime: value?.[1]?.valueOf?.() || '',
          }),
        },
      },
      {
        title: '请求路径',
        dataIndex: 'url',
        search: false,
        width: 220,
        ellipsis: true,
      },
      {
        title: '操作状态',
        dataIndex: 'exception',
        search: false,
        width: 100,
        align: 'center',
        render: (_, record) =>
          record.exception ? <Tag color="error">失败</Tag> : <Tag color="success">成功</Tag>,
      },
      {
        title: '操作人',
        dataIndex: 'loginname',
        search: false,
        width: 180,
        render: (_, record) =>
          record.loginname ? `${record.username || ''}(${record.loginname})` : '-',
      },
      {
        title: '操作时间',
        dataIndex: 'createdAt',
        search: false,
        width: 180,
        sorter: true,
        render: (_, record) =>
          record.createdAt ? dayjs(record.createdAt).format('YYYY-MM-DD HH:mm:ss') : '-',
      },
      {
        title: 'IP',
        dataIndex: 'ip',
        search: false,
        width: 140,
      },
      {
        title: '执行耗时',
        dataIndex: 'executeTime',
        search: false,
        width: 100,
        align: 'center',
        render: (_, record) =>
          typeof record.executeTime === 'number' ? `${record.executeTime} ms` : '-',
      },
      {
        title: '操作',
        key: 'option',
        valueType: 'option',
        width: 180,
        render: (_, record) => [
          <Button
            key="detail"
            type="link"
            icon={<EyeOutlined />}
            onClick={() => setDetailRecord(record)}
          >
            详情
          </Button>,
          <Button
            key="delete"
            type="link"
            danger
            icon={<DeleteOutlined />}
            disabled={!access.hasPermission('sys.manage.log.delete')}
            onClick={() => {
              modal.confirm({
                title: '确认删除日志',
                content: '确定删除该日志记录吗？',
                onOk: async () => {
                  await deleteLog(record.id, record.createdAt);
                  actionRef.current?.reload();
                },
              });
            }}
          >
            删除
          </Button>,
        ],
      },
    ],
    [access, apps, metaLoading, modal, types],
  );

  return (
    <PageContainer title="系统日志">
      <PlatformProTable<SysLogRecord, LogTableParams>
        persistenceKey="platform-sys-log-table"
        actionRef={actionRef}
        rowKey="id"
        headerTitle="日志列表"
        dateFormatter={false}
        columns={columns}
        toolBarRender={() => [
          <Button
            key="clear"
            danger
            disabled={!access.hasPermission('sys.manage.log.delete')}
            onClick={() => {
              modal.confirm({
                title: '确认清空日志',
                content: '确定清空当前筛选条件下的日志记录吗？未筛选时将清空全部日志。',
                onOk: async () => {
                  await clearLogs({
                    ...latestFiltersRef.current,
                    pageNo: 1,
                    pageSize: actionRef.current?.pageInfo?.pageSize || 10,
                    totalCount: 0,
                    ...latestSortRef.current,
                  });
                  actionRef.current?.reload();
                },
              });
            }}
          >
            清空日志
          </Button>,
        ]}
        request={async (params, sort) => {
          const sortParams = getSortParams(sort, 'createdAt');
          latestFiltersRef.current = {
            appId: params.appId || '',
            type: params.type || '',
            status: params.status || '',
            loginname: params.loginname || '',
            username: params.username || '',
            tag: params.tag || '',
            msg: params.msg || '',
            beginTime: (params as Record<string, any>).beginTime || '',
            endTime: (params as Record<string, any>).endTime || '',
          };
          latestSortRef.current = sortParams;
          const response = await getLogPage({
            ...latestFiltersRef.current,
            pageNo: params.current || 1,
            pageSize: params.pageSize || 10,
            totalCount: 0,
            ...sortParams,
          });
          return {
            data: response.data.list || [],
            total: response.data.totalCount || 0,
            success: true,
          };
        }}
      />

      <Drawer
        title="日志详情"
        open={Boolean(detailRecord)}
        size="large"
        onClose={() => setDetailRecord(undefined)}
      >
        {detailRecord ? (
          <Descriptions column={1} bordered size="small">
            <Descriptions.Item label="操作人">
              {detailRecord.loginname
                ? `${detailRecord.username || ''}(${detailRecord.loginname})`
                : '-'}
            </Descriptions.Item>
            <Descriptions.Item label="操作时间">
              {detailRecord.createdAt
                ? dayjs(detailRecord.createdAt).format('YYYY-MM-DD HH:mm:ss')
                : '-'}
            </Descriptions.Item>
            <Descriptions.Item label="操作IP">{detailRecord.ip || '-'}</Descriptions.Item>
            <Descriptions.Item label="请求路径">{detailRecord.url || '-'}</Descriptions.Item>
            <Descriptions.Item label="执行方法">{detailRecord.method || '-'}</Descriptions.Item>
            <Descriptions.Item label="操作系统">{detailRecord.os || '-'}</Descriptions.Item>
            <Descriptions.Item label="浏览器">{detailRecord.browser || '-'}</Descriptions.Item>
            <Descriptions.Item label="请求参数">
              <Typography.Paragraph style={{ whiteSpace: 'pre-wrap', marginBottom: 0 }}>
                {detailRecord.params || '-'}
              </Typography.Paragraph>
            </Descriptions.Item>
            <Descriptions.Item label="响应结果">
              <Typography.Paragraph style={{ whiteSpace: 'pre-wrap', marginBottom: 0 }}>
                {detailRecord.result || '-'}
              </Typography.Paragraph>
            </Descriptions.Item>
            {detailRecord.exception ? (
              <Descriptions.Item label="异常信息">
                <Typography.Paragraph style={{ whiteSpace: 'pre-wrap', marginBottom: 0 }}>
                  {detailRecord.exception}
                </Typography.Paragraph>
              </Descriptions.Item>
            ) : null}
          </Descriptions>
        ) : null}
      </Drawer>
    </PageContainer>
  );
};

export default LogPage;

// budiot-vue-admin/src/views/platform/sys/log/index.vue
<template>
    <div class="app-container">
        <el-row>
            <el-form :model="queryParams" ref="queryRef" :inline="true" v-show="showSearch" label-width="68px">
                    <el-form-item label="用户姓名" prop="username">
                        <el-input
v-model="queryParams.username" placeholder="请输入用户姓名" clearable style="width: 180px"
                            @keyup.enter="handleSearch" />
                    </el-form-item>
                    <el-form-item label="用户名" prop="loginname">
                        <el-input
v-model="queryParams.loginname" placeholder="请输入用户名" clearable style="width: 180px"
                            @keyup.enter="handleSearch" />
                    </el-form-item>
                    <el-form-item label="功能模块" prop="tag">
                        <el-input
v-model="queryParams.tag" placeholder="请输入功能模块" clearable style="width: 180px"
                            @keyup.enter="handleSearch" />
                    </el-form-item>
                    <el-form-item label="日志内容" prop="msg">
                        <el-input
v-model="queryParams.msg" placeholder="请输入日志内容" clearable style="width: 180px"
                            @keyup.enter="handleSearch" />
                    </el-form-item>
                    <el-form-item label="操作状态" prop="status">
                        <el-radio-group v-model="queryParams.status" placeholder="操作状态" @change="statusChange">
                            <el-radio :value="''">全部</el-radio>
                            <el-radio :value="'success'">成功</el-radio>
                            <el-radio :value="'exception'">失败</el-radio>
                        </el-radio-group>
                    </el-form-item>
                    <el-form-item label="操作时间" prop="dateRange" style="font-weight:700;width: 325px;">
                        <el-date-picker
v-model="dateRange" type="daterange" range-separator="-"
                            start-placeholder="开始日期" end-placeholder="结束日期" value-format="x"></el-date-picker>
                    </el-form-item>
                    <el-form-item>
                        <el-button type="primary" icon="Search" @click="handleSearch">搜索</el-button>
                        <el-button icon="Refresh" @click="resetSearch">重置</el-button>
                    </el-form-item>
                </el-form>
        </el-row>
        <el-row :gutter="10" class="mb8">
            <el-col :span="1.5">
                <el-radio-group v-model="queryParams.type" placeholder="日志类型" @change="typeChange">
                            <el-radio-button :value="''">全部日志</el-radio-button>
                            <el-radio-button :value="item.value" v-for="(item) in types" :key="item.value">{{ item.text }}</el-radio-button>
                </el-radio-group>
            </el-col>
            <el-col :span="1.5">
                <el-select v-model="appId" class="m-2" placeholder="选择应用" @change="appChange" clearable>
                    <el-option v-for="item in apps" :key="item.id" :label="item.name" :value="item.id" />
                </el-select>
            </el-col>
                <right-toolbar
v-model:showSearch="showSearch" :extendSearch="true" :columns="columns"
                        @quickSearch="handleSearch" />
        </el-row>
        <el-table v-loading="tableLoading" :data="tableData" row-key="id" stripe  @sort-change="sortChange" :default-sort="defaultSort">
            <template v-for="(item, idx) in columns" :key="idx">
                <el-table-column :prop="item.prop" :label="item.label" :fixed="item.fixed" v-if="item.show"
                    :show-overflow-tooltip="true" :align="item.align" :width="item.width" :sortable="item.sortable">
                    <template v-if="item.prop == 'exception'" #default="scope">
                        <el-tag v-if="scope.row.exception" :disable-transitions="true" type="danger">失败</el-tag>
                        <el-tag v-else :disable-transitions="true" type="success">成功</el-tag>
                    </template>
                    <template v-if="item.prop == 'loginname'" #default="scope">
                        <span v-if="scope.row.loginname">{{ scope.row.username }}({{ scope.row.loginname }})</span>
                    </template>
                    <template v-if="item.prop == 'createdAt'" #default="scope">
                        <span>{{ formatTime(scope.row.createdAt) }}</span>
                    </template>
                    <template v-if="item.prop == 'executeTime'" #default="scope">
                        <span class="time">{{ scope.row.executeTime }}ms</span>
                    </template>
                </el-table-column>
            </template>
            <el-table-column fixed="right" header-align="center" align="center" width="70" label="操作"
                class-name="small-padding fixed-width">
                <template #default="scope">
                    <el-tooltip content="查看详情" placement="top">
                        <el-button link type="primary" icon="View" @click="handleView(scope.row)"></el-button>
                    </el-tooltip>
                </template>
            </el-table-column>
        </el-table>
        <el-row>
            <pagination :total="queryParams.totalCount" v-model:page="queryParams.pageNo"
                v-model:limit="queryParams.pageSize" @pagination="list" />
        </el-row>

        <el-drawer v-model="showDetail" direction="rtl" title="日志详情" size="50%">

            <template #default>
                <el-form :model="formData" label-width="80px">
                    <el-row>
                        <el-col :span="12">
                            <el-form-item label="操作人" prop="loginname">
                                <span v-if="formData.loginname">{{ formData.username }}({{ formData.loginname }})</span>
                            </el-form-item>
                        </el-col>
                        <el-col :span="12">
                            <el-form-item label="操作时间" prop="createdAt">
                                {{ formatTime(formData.createdAt) }}
                            </el-form-item>
                        </el-col>
                        <el-col :span="12">
                            <el-form-item label="操作IP" prop="ip">
                                {{ formData.ip }}
                            </el-form-item>
                        </el-col>
                        <el-col :span="12">
                            <el-form-item label="请求路径" prop="url">
                                {{ formData.url }}
                            </el-form-item>
                        </el-col>
                        <el-col :span="12">
                            <el-form-item label="执行方法" prop="method">
                                {{ formData.method }}
                            </el-form-item>
                        </el-col>
                        <el-col :span="24">
                            <el-form-item label="操作系统" prop="os">
                                {{ formData.os }}
                            </el-form-item>
                        </el-col>
                        <el-col :span="24">
                            <el-form-item label="浏览器" prop="browser" class="content">
                                {{ formData.browser }}
                            </el-form-item>
                        </el-col>
                        <el-col :span="24">
                            <el-form-item label="请求参数" prop="params" class="content">
                                {{ formData.params }}
                            </el-form-item>
                        </el-col>
                        <el-col :span="24">
                            <el-form-item label="响应结果" prop="result" class="content">
                                {{ formData.result }}
                            </el-form-item>
                        </el-col>
                        <el-col :span="24" v-if="formData.exception">
                            <el-form-item label="异常信息" prop="exception" class="content">
                                {{ formData.exception }}
                            </el-form-item>
                        </el-col>
                    </el-row>
                </el-form>
            </template>
        </el-drawer>
    </div>
</template>
<script setup lang="ts" name="platform-sys-log">
import { nextTick, onMounted, reactive, ref } from 'vue'
import modal from '/@/utils/modal'
import { getList, getData } from '/@/api/platform/sys/log'
import { toRefs } from '@vueuse/core'
import { ElForm } from 'element-plus'
import { addDateRange } from '/@/utils/common'

const createRef = ref<InstanceType<typeof ElForm>>()
const updateRef = ref<InstanceType<typeof ElForm>>()
const queryRef = ref<InstanceType<typeof ElForm>>()

const showSearch = ref(true)    
const showCreate = ref(false)
const showUpdate = ref(false)
const tableLoading = ref(false)
const tableData = ref([])
const apps = ref([])
const types = ref([])
const showDetail = ref(false)
const appId = ref('')
const dateRange =ref([])

const defaultSort = ref({ prop: "createdAt", order: "descending" });

const data = reactive({
    formData: {},
    queryParams: {
        appId: '',
        type: '',
        status: '',
        loginname: '',
        username: '',
        tag: '',
        msg: '',
        beginTime: '',
        endTime: '',
        pageNo: 1,
        pageSize: 10,
        totalCount: 0,
        pageOrderName: 'createdAt',
        pageOrderBy: 'descending'
    },
})

const { formData, queryParams } = toRefs(data)

const columns = ref([
    { prop: 'url', label: `请求路径`, show: true, fixed: 'left', width: 200 },
    { prop: 'tag', label: `功能模块`, show: true, fixed: 'left', width: 100 },
    { prop: 'msg', label: `日志内容`, show: true, fixed: false },
    { prop: 'exception', label: `操作状态`, show: true, fixed: false, align: 'center', width: 80 },
    { prop: 'loginname', label: `操作人`, show: true, fixed: false },
    { prop: 'createdAt', label: `操作时间`, show: true, fixed: false, width: 160, sortable: true },
    { prop: 'ip', label: `IP`, show: true, fixed: false, width: 100 },
    { prop: 'executeTime', label: `执行耗时`, show: true, fixed: false, align: 'center', width: 80 }
])

const handleView = (row: any) => {
    formData.value = row
    showDetail.value = true
}

// 查询表格
const list = () => {
    tableLoading.value = true
    addDateRange(queryParams.value, dateRange.value)
    getList(queryParams.value).then((res) => {
        tableLoading.value = false
        tableData.value = res.data.list as never
        queryParams.value.totalCount = res.data.totalCount as never
    })
}

const statusChange = () => {
    handleSearch()
}

const typeChange = () => {
    handleSearch()
}

const sortChange = (column: any) => {
    queryParams.value.pageOrderName = column.prop
    queryParams.value.pageOrderBy = column.order
    handleSearch()
}

// 刷新
const handleSearch = () => {
    queryParams.value.pageNo = 1
    queryParams.value.appId = appId.value
    list()
}

// 重置搜索
const resetSearch = () => {
    queryRef.value?.resetFields()
    list()
}

const getInitData = () => {
    getData().then((res)=>{
        apps.value = res.data.apps
        types.value = res.data.types
    })
}

const appChange = (val: string) => {
    handleSearch()
}

onMounted(() => {
    list()
    getInitData()
})
</script>
<!--定义布局-->
<route lang="yaml">
    meta:
      layout: platform/index
</route>
<style scoped>
.time {
    font-size: 11px;
    background-color: rgb(135, 208, 104);
    color: #fff;
    display: inline-block;
    width: 38px;
    border-radius: 2px;
    padding-left: 1px;
    height: 22px;
}
.content {
    white-space:normal; 
    word-break:break-all;
}
</style>
